import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
      <meta name="google-site-verification" content="0vvzgCPSYDeR6cxy-7czoAPcVnv1zobb7l50nXsVE8A" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
